version: '3'

services:


 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dksdlfduq2
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mobiusdb
    ports:
      - "3306:3306"
    network_mode: "host"
    volumes:
      - ./Mobius/sql:/docker-entrypoint-initdb.d

 node:
    image: "node:7.6"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./Mobius:/home/node/app
    network_mode: "host"
    expose:
      - "8081"
    command: "node mobius"
    depends_on:
      - db
 mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    network_mode: "host"
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
      - db